###############
## 
####

GPU: [0]

VERBOSE: True

MODEL:
  MODE: 'Denoising'
  SESSION: 'ECNNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 16
  NUM_EPOCHS: 120
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 140
  VAL_PS: 256
  TRAIN_DIR: './Datasets/train' # path to training data
  VAL_DIR: './Datasets/SIDD/val'     # path to validation data
  SAVE_DIR: './checkpoints'          # path to save models and images
  # SAVE_IMAGES: False
